### ISSUE TITLE
fix(button.tsx)

### ISSUE THREAD

**Issue by thenameiswiiwin** [frontendfyi/rebuilding-linear.app#2]
There is an error with variant secondary button spacing first and last child for [&_.highlight]

**Comment by thenameiswiiwin** [comment]
[&_.highlight]:last:-ml-2 [&_.highlight]:last:mr-2 [&_.highlight]:first:ml-2 [&_.highlight]:first:-mr-2

**Comment by JeroenReumkens** [comment]
Oh yes, great spot! I also spotted it myself recently and fixed that. I overlooked this issue because my github issues were messed up a bit. So sorry for my late response, really appreciate your issue though 🙏
